// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: auth.proto
// </auto-generated>
#pragma warning disable 1591
using pbr = global::Google.Protobuf.Reflection;

namespace auth {
  public static partial class AuthReflection {
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "CgphdXRoLnByb3RvEgRhdXRoIjAKC0F1dGhSZXF1ZXN0EhIKC2NyZWRlbnRpYWxzGAEgASgMUg" +
          "tjcmVkZW50aWFscyIjCgxBdXRoUmVzcG9uc2USEgoFdG9rZW4YASABKAlSBXRva2VuMkYKBkF1" +
          "dGgSKwoMQXV0aGVudGljYXRlEhUuYXV0aC5BdXRoUmVxdWVzdBoWLmF1dGguQXV0aFJlc3Bvbn" +
          "NlIgAwYgZwcm90bzM="
      );
      descriptor = pbr::FileDescriptor.FromGeneratedCode(
          descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(
              new[] { typeof(global::auth.AuthRequest), typeof(global::auth.AuthResponse) }, null)
      );
    }
  }
}
#pragma warning restore 1591
