// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: auth.proto
// </auto-generated>
#pragma warning disable 1591
using Grpc.Core;
using Grpc.Net.Client;
using Grpc.Net.Client.Web;

namespace auth {
  public static partial class Auth
  {
    static readonly string __ServiceName = "auth.Auth";

    static readonly Method<AuthRequest, AuthResponse> __Method_Authenticate =
      new Method<AuthRequest, AuthResponse>(
          MethodType.Unary,
          __ServiceName,
          "Authenticate",
          Marshallers.Create(
              r => Google.Protobuf.MessageExtensions.ToByteArray(r),
              data => AuthRequest.Parser.ParseFrom(data)),
          Marshallers.Create(
              r => Google.Protobuf.MessageExtensions.ToByteArray(r),
              data => AuthResponse.Parser.ParseFrom(data)));

    public partial class AuthClient
    {
      private readonly CallInvoker callInvoker;

      public AuthClient(GrpcChannel channel) {
        callInvoker = channel.CreateCallInvoker();
      }

      public virtual AsyncUnaryCall<AuthResponse> AuthenticateAsync(AuthRequest request, System.Threading.CancellationToken cancellationToken = default) {
        return callInvoker.AsyncUnaryCall(__Method_Authenticate, null, new CallOptions(cancellationToken: cancellationToken), request);
      }
    }
  }
}
#pragma warning restore 1591
